### ISSUE TITLE
Error ChatGPT 400

### ISSUE THREAD

**Issue by NotFlyLoongQaQ** [0xk1h0/ChatGPT_DAN#18]
Return:
undefined
[ChatGPT error 400: {"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}]

**Comment by isaaclins** [comment]
refresh the site, clear your chatlogs, open a new chat and insert the same prompt as you gave it.

**Comment by 0xk1h0** [comment]
Since this is a fixable issue, we'll close the issue.
