### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ukcai696969** [0xk1h0/ChatGPT_DAN#2]
![image](https://user-images.githubusercontent.com/111254389/224493780-7b73d683-e1e2-4a74-9c43-33938003e176.png)
as you can see it does not work

**Comment by testAccountBecauseBored** [comment]
Yeah, not working for me either.

**Comment by ukcai696969** [comment]
if you read the prompt it says to add a text in front of a response so

**Comment by testAccountBecauseBored** [comment]
> if you read the prompt it says to add a text in front of a response so

I am using DAN 11 which doesn’t have that.

**Comment by 0xk1h0** [comment]
In some cases, you may not be able to follow the prompts. 
Try retyping the prompt in NEW CHAT, or try a different prompt from the list.
