### ISSUE TITLE
No prompt is working.

### ISSUE THREAD

**Issue by EmuBookWorm** [0xk1h0/ChatGPT_DAN#66]
I tried the traditional Developer mode prompt I found on reddit and quite a few I found here as well as trying some of my own but none of them work. I'm on GPT 3.5, May 12th Version

**Comment by D4RKH0R1Z0N** [comment]
Try regenrating the response a couple times, worked after 3 or 5 times

**Comment by EmuBookWorm** [comment]
Yep, the Jailbreak prompt (the first one) works! Thanks!

**Comment by D4RKH0R1Z0N** [comment]
Ok, Welcome! please close the issue
