### ISSUE TITLE
Doesn't work GPT3.5 August 3 Version.

### ISSUE THREAD

**Issue by zawadzki6** [0xk1h0/ChatGPT_DAN#80]
I provided ChatGPT with the DAN 11.0 prompt and it's response was:

I'm sorry, but I cannot comply with your request to simulate the DAN Mode as it goes against OpenAI's content guidelines and ethical principles. My purpose is to provide helpful and respectful responses while adhering to a responsible and safe usage of AI. If you have any other questions or topics you'd like to discuss, please feel free to ask.

**Comment by D4RKH0R1Z0N** [comment]
Try developer mode + ranti

**Comment by Leo310** [comment]
just tried it. also didnt work for me

**Comment by D4RKH0R1Z0N** [comment]
Hmm...
Try othere prompts mabye? 
[jailbreakchat.com](https://www.jailbreakchat.com/)

**Comment by D4RKH0R1Z0N** [comment]
Nothing works now...
