### ISSUE TITLE
Solution to non-working prompts!

### ISSUE THREAD

**Issue by D4RKH0R1Z0N** [0xk1h0/ChatGPT_DAN#89]
https://flowgpt.com/prompt/j8cbd_aNaPivvUUP3siE3?isModal=true

Actually works (5th September 2023)
It can do anything, I told it to give the recipe for m#th, it actually gave it

**Comment by sTiKyt** [comment]
Misleading name, not a solution, just an alternative.

**Comment by D4RKH0R1Z0N** [comment]
lol
